name: CD Pipeline

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull demian996/cicd-pipeline:latest
    - name: Delete Old docker container
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 80:80 --name cicd-pipeline-container demian996/cicd-pipeline