name: CD Pipeline

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🔑 Configurar SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: 🐳 Login a Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 🚀 Desplegar en EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # Actualizar imágenes
          docker pull demian996/cicd-pipeline:latest
          
          # Detener y limpiar
          docker stop cicd-pipeline-container || true
          docker rm cicd-pipeline-container || true
          
          # Ejecutar nuevo contenedor
          docker run -d \
            --name cicd-pipeline-container \
            -p 80:80 \
            --restart unless-stopped \
            demian996/cicd-pipeline:latest
          
          # Limpieza
          docker system prune -af
        EOF