name: Continuous Integration

on:
  push:
    branches: [ main, master ]  # Se activa en push a main o master
  pull_request:
    branches: [ main, master ]  # También en PRs hacia estas ramas

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Login Dockerhub
      if: ${{ github.event_name == 'push' }}
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t demian996/cicd-pipeline .
    - name: Push to Dockerhub
      run: docker push demian996/cicd-pipeline:latest

