name: Continuous Integration

on:
  push:
    branches: [ main, master ]  # Se activa en push a main o master
  pull_request:
    branches: [ main, master ]  # También en PRs hacia estas ramas

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate HTML structure
      run: |
        if ! grep -q '<!DOCTYPE html>' index.html; then
          echo "❌ Error: Falta DOCTYPE en index.html"
          exit 1
        fi
        echo "✅ HTML structure valid"

    - name: Validate JavaScript syntax
      run: |
        if ! node -e "require('./script.js')"; then
          echo "❌ Error: Syntax error in script.js"
          exit 1
        fi
        echo "✅ JavaScript syntax valid"

    - name: Check CSS validity
      run: |
        if ! grep -q 'body {' style.css; then
          echo "❌ Error: CSS structure issue"
          exit 1
        fi
        echo "✅ CSS structure valid"